version: "2"

networks:
  byfn:

services:
  consul-server:
    image: consul:latest
    container_name: consul-server
    command: agent -server -bootstrap-expect=1 -node=consul-server -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    networks:
    - byfn

  consul-client:
    image: consul:latest
    container_name: consul-client
    command: agent -retry-join=consul-server -node=consul-client -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    ports:
    - 8500:8500
    depends_on:
    - consul-server
    networks:
    - byfn